namespace SupportApp.Dtos
    {
    // For creation, we typically don't include the Id since it's generated by the database. We can also have a separate DTO for updates if we want to allow partial updates (e.g. only email).
    public class AgentCreateDto
        {
        public string DisplayName { get; set; } = null!;
        public string Email { get; set; } = null!;
        }
    // For update, we can reuse the same DTO as create, or have a separate one if we want to allow partial updates (e.g. only email).
    public class AgentReadDto
        {
        public int Id { get; set; }
        public string DisplayName { get; set; } = null!;
        public string Email { get; set; } = null!;
        public bool isActive { get; set; } = true;
        }
    }